"""Private, read-only report portal. Intended to run behind the local Nginx gateway."""
from __future__ import annotations

from collections import deque
import hashlib
import hmac
from http.cookies import SimpleCookie
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import io
import json
import math
import os
from pathlib import Path
import re
import secrets
import stat
import threading
import time
from urllib.parse import parse_qs, unquote, urlsplit
import zipfile

from .artifacts import finding_fingerprint, finding_list

NAME = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]{0,159}\Z")
FILE_LIMIT = 8 * 1024 * 1024
ARCHIVE_LIMIT = 64 * 1024 * 1024
RESULT_FILES = {"report.md", "findings.json", "coverage.json", "scan-manifest.json", "results.sarif"}
ROOT_FILES = {"run-manifest.json", "aggregate.json", "target-revision.txt"}
ASSETS = Path(__file__).with_name("web")


def _job(name):
    return name.split("-", 1)[0] in {"triage", "verifier", "primary", "deep"}


def allowed_artifact(path: str) -> bool:
    parts = path.split("/")
    if not all(NAME.fullmatch(p) and p not in {".", ".."} for p in parts):
        return False
    if len(parts) == 1:
        return path in ROOT_FILES
    # Job directories are generated by the runner, not arbitrary output folders.
    if not _job(parts[0]):
        return False
    if len(parts) == 2:
        return parts[1] in {"results.sarif", "verification-manifest.json"}
    if len(parts) == 3:
        return parts[1] == "results" and parts[2] in RESULT_FILES
    if len(parts) == 5:
        return parts[1] == "candidates" and parts[4] == "results.sarif"
    if len(parts) == 6:
        return parts[1] == "candidates" and parts[4] == "results" and parts[5] in RESULT_FILES
    return False


def _dict(value):
    return value if isinstance(value, dict) else {}


def _list(value):
    return value if isinstance(value, list) else []


class ReportStore:
    """Open every component relative to a pinned directory fd, without following links."""

    def __init__(self, root: Path):
        self.fd = os.open(root, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)

    def close(self):
        os.close(self.fd)

    def _open(self, parts: list[str], directory=False):
        if not parts or not all(NAME.fullmatch(p) and p not in {".", ".."} for p in parts):
            raise FileNotFoundError("invalid report path")
        fd = os.dup(self.fd)
        try:
            for index, part in enumerate(parts):
                flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK
                if index < len(parts) - 1 or directory:
                    flags |= os.O_DIRECTORY
                new_fd = os.open(part, flags, dir_fd=fd)
                os.close(fd)
                fd = new_fd
            return fd
        except BaseException:
            os.close(fd)
            raise

    def read(self, run_id: str, path: str) -> bytes:
        if not allowed_artifact(path):
            raise FileNotFoundError("not a downloadable report")
        fd = self._open([run_id, *path.split("/")])
        with os.fdopen(fd, "rb") as stream:
            metadata = os.fstat(stream.fileno())
            if not stat.S_ISREG(metadata.st_mode) or metadata.st_size > FILE_LIMIT:
                raise ValueError("report exceeds size limit or is not a regular file")
            data = stream.read(FILE_LIMIT + 1)
            if len(data) > FILE_LIMIT:
                raise ValueError("report exceeds size limit")
            return data

    def document(self, run_id: str, path: str):
        try:
            def reject_constant(value):
                raise ValueError("non-finite JSON number")
            return json.loads(self.read(run_id, path), parse_constant=reject_constant)
        except (OSError, ValueError, RecursionError):
            return None

    def run_ids(self):
        with os.scandir(self.fd) as entries:
            return sorted((e.name for e in entries if NAME.fullmatch(e.name)
                           and not e.name.startswith(".") and e.is_dir(follow_symlinks=False)),
                          reverse=True)

    def artifacts(self, run_id: str):
        found = []
        visited = 0

        def visit(parts):
            nonlocal visited
            fd = self._open([run_id, *parts], directory=True)
            try:
                with os.scandir(fd) as entries:
                    for entry in entries:
                        visited += 1
                        if visited > 5000:
                            raise ValueError("too many report entries")
                        if not NAME.fullmatch(entry.name) or entry.name.startswith("."):
                            continue
                        child = [*parts, entry.name]
                        path = "/".join(child)
                        if entry.is_file(follow_symlinks=False) and allowed_artifact(path):
                            size = entry.stat(follow_symlinks=False).st_size
                            found.append({"path": path, "size": size, "available": size <= FILE_LIMIT})
                        elif entry.is_dir(follow_symlinks=False) and len(child) < 6:
                            if len(child) == 1 and not _job(entry.name):
                                continue
                            if len(child) == 2 and entry.name not in {"results", "candidates"}:
                                continue
                            try:
                                visit(child)
                            except OSError:
                                continue  # Concurrent scanner writes/renames are normal.
            finally:
                os.close(fd)

        visit([])
        return sorted(found, key=lambda item: item["path"])

    def summary(self, run_id: str):
        manifest = self.document(run_id, "run-manifest.json")
        aggregate = self.document(run_id, "aggregate.json")
        warnings = []
        if not isinstance(manifest, dict):
            warnings.append("运行清单缺失或无法解析")
        if not isinstance(aggregate, dict):
            warnings.append("汇总缺失或无法解析；发现数量未知")
        manifest, aggregate = _dict(manifest), _dict(aggregate)
        results = [_dict(r) for r in _list(manifest.get("results"))]
        effective = [r for r in results if r.get("counts_toward_exit", True)]
        codes = [r.get(key) for r in effective for key in ("returncode", "export_returncode")
                 if r.get(key) is not None]
        if not manifest:
            status = "unknown"
        elif manifest.get("dry_run"):
            status = "dry_run"
        elif not manifest.get("completed_at"):
            status = "unfinished"
        elif any(code not in (0, 2) for code in codes):
            status = "failed"
        elif manifest.get("partial_coverage") or 2 in codes:
            status = "partial"
        elif not effective or not codes or not aggregate or aggregate.get("unreadable_artifacts"):
            status = "unknown"
        else:
            status = "completed"
        if status == "completed":
            try:
                coverage_files = [item["path"] for item in self.artifacts(run_id)
                                  if item["path"].endswith("/coverage.json")]
                coverage = [self.document(run_id, path) for path in coverage_files]
                if not coverage or any(not isinstance(item, dict) or item.get("completeness") not in ("complete", "partial") for item in coverage):
                    status = "unknown"
                    warnings.append("缺少有效的覆盖记录")
                elif any(item.get("completeness") == "partial" for item in coverage):
                    status = "partial"
            except (OSError, ValueError):
                status = "unknown"
                warnings.append("无法核验覆盖记录")
        if aggregate.get("unreadable_artifacts"):
            warnings.append("存在无法读取的报告产物")
        cost = 0.0
        has_cost = False
        for result in results:  # Include failed/fallback attempts in usage.
            value = result.get("estimated_cost")
            if isinstance(value, (int, float)) and math.isfinite(value) and value >= 0:
                cost += value
                has_cost = True
        plan = _dict(manifest.get("plan"))
        jobs = [_dict(j) for j in _list(plan.get("jobs"))]
        models = {str(r["model"]) for r in results if r.get("model")}
        models.update(str(_dict(j.get("profile"))["model"]) for j in jobs if _dict(j.get("profile")).get("model"))
        count = aggregate.get("finding_group_count")
        return {"id": run_id, "status": status, "created_at": manifest.get("created_at"),
                "completed_at": manifest.get("completed_at"),
                "finding_count": count if isinstance(count, int) and count >= 0 else None,
                "estimated_cost": round(cost, 6) if has_cost else None,
                "models": sorted(models), "mode": plan.get("run_mode") or plan.get("mode"),
                "scopes": sorted({str(_dict(j.get("scope")).get("id", j.get("scope_id", ""))) for j in jobs} - {""}),
                "warnings": warnings}

    def detail(self, run_id: str):
        artifacts = self.artifacts(run_id)  # Also establishes that this is a real directory.
        summary = self.summary(run_id)
        coverages = []
        deferred = []
        for item in artifacts:
            if item["path"].endswith("/coverage.json"):
                document = self.document(run_id, item["path"])
                if not isinstance(document, dict):
                    summary["warnings"].append("覆盖文件无法解析: " + item["path"])
                    if summary["status"] == "completed":
                        summary["status"] = "unknown"
                    continue
                coverages.append({"path": item["path"], "document": document})
                deferred.extend({"source": item["path"], "item": value}
                                for value in _list(document.get("deferred")))
                if document.get("completeness") == "partial" and summary["status"] == "completed":
                    summary["status"] = "partial"
        if not coverages and summary["status"] == "completed":
            summary["status"] = "unknown"
            summary["warnings"].append("没有可核验的覆盖记录")
        try:
            revision = self.read(run_id, "target-revision.txt").decode("utf-8").strip()
        except (OSError, ValueError):
            revision = None
        groups = []
        # Resolve details from enumerated, allowlisted report files only. Never open
        # the model-controlled absolute `source` paths stored in the aggregate.
        finding_index = {}
        for artifact in artifacts:
            path = artifact["path"]
            if artifact["available"] and path.endswith("/results/findings.json"):
                for finding in finding_list(self.document(run_id, path)):
                    key = (path.split("/", 1)[0], finding_fingerprint(finding))
                    finding_index.setdefault(key, []).append((path, finding))
        for group in _list(_dict(self.document(run_id, "aggregate.json")).get("finding_groups")):
            if isinstance(group, dict):
                occurrences = []
                for value in _list(group.get("occurrences")):
                    if not isinstance(value, dict):
                        continue
                    occurrence = dict(value)
                    profile, fingerprint = value.get("profile"), group.get("fingerprint")
                    matches = finding_index.get((profile, fingerprint), []) if isinstance(profile, str) and isinstance(fingerprint, str) else []
                    source = value.get("source")
                    if isinstance(source, str) and source:
                        matches = [(path, finding) for path, finding in matches
                                   if source == path or source.endswith("/" + run_id + "/" + path)]
                    if len(matches) == 1:
                        occurrence.update(artifact_path=matches[0][0], finding=matches[0][1])
                    else:
                        occurrence.update(artifact_path=None, finding=None,
                                          detail_warning="未能唯一匹配原始发现文件；请查看原始报告")
                    occurrences.append(occurrence)
                groups.append({**group, "profiles": _list(group.get("profiles")),
                               "occurrences": occurrences})
        return {**summary, "revision": revision, "artifacts": artifacts,
                "finding_groups": groups,
                "coverage": coverages, "deferred": deferred}

    def archive(self, run_id: str) -> bytes:
        output = io.BytesIO()
        size = 0
        with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as archive:
            for item in self.artifacts(run_id):
                if not item["available"]:
                    raise ValueError("an artifact is too large; download individual files instead")
                data = self.read(run_id, item["path"])
                size += len(data)
                if size > ARCHIVE_LIMIT:
                    raise ValueError("archive exceeds size limit; download individual files instead")
                archive.writestr(f"{run_id}/{item['path']}", data)
        return output.getvalue()


def init_auth(auth_file: Path, login_file: Path, username: str = "reviewer"):
    if not re.fullmatch(r"[a-zA-Z0-9_-]{1,64}", username):
        raise ValueError("username must contain only letters, digits, underscores or hyphens")
    if auth_file.exists() or login_file.exists():
        raise ValueError("credentials already exist; move both files aside before an explicit rotation")
    password = secrets.token_urlsafe(24)
    salt = secrets.token_bytes(32)
    document = {"username": username, "iterations": 600000, "salt": salt.hex(),
                "digest": hashlib.pbkdf2_hmac("sha256", password.encode(), salt, 600000).hex()}
    # Exclusive creation avoids silently replacing live credentials.
    for path, value in ((auth_file, json.dumps(document) + "\n"),
                        (login_file, f"username={username}\npassword={password}\n")):
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w") as stream:
            stream.write(value)


class Auth:
    def __init__(self, path: Path):
        data = json.loads(path.read_text())
        self.username = data["username"]
        self.salt = bytes.fromhex(data["salt"])
        self.digest = bytes.fromhex(data["digest"])
        self.iterations = int(data["iterations"])
        if not (200000 <= self.iterations <= 1000000 and len(self.salt) == 32 and len(self.digest) == 32):
            raise ValueError("invalid authentication configuration")
        self.sessions = {}
        self.attempts = deque()
        self.lock = threading.Lock()

    def login(self, username: str, password: str):
        now = time.monotonic()
        with self.lock:
            while self.attempts and self.attempts[0] <= now - 300:
                self.attempts.popleft()
            if len(self.attempts) >= 15:
                return None, 429
            self.attempts.append(now)
        digest = hashlib.pbkdf2_hmac("sha256", password.encode(), self.salt, self.iterations)
        if not (hmac.compare_digest(digest, self.digest) and hmac.compare_digest(username.encode(), self.username.encode())):
            return None, 401
        with self.lock:
            self.sessions = {k: expiry for k, expiry in self.sessions.items() if expiry > now}
            if len(self.sessions) >= 128:
                self.sessions.pop(next(iter(self.sessions)))
            token = secrets.token_urlsafe(32)
            self.sessions[token] = now + 8 * 3600
        return token, 200

    def valid(self, token):
        with self.lock:
            return self.sessions.get(token, 0) > time.monotonic()

    def logout(self, token):
        with self.lock:
            self.sessions.pop(token, None)


class ReportServer(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(self, address, store, auth, base_path="/security", secure_cookie=False):
        self.store, self.auth = store, auth
        if not re.fullmatch(r"(?:/[A-Za-z0-9_-]+)+", base_path):
            raise ValueError("base path must be a simple absolute URL path")
        self.base_path, self.secure_cookie = base_path, secure_cookie
        self.slots = threading.BoundedSemaphore(12)
        self.archive_slot = threading.BoundedSemaphore(1)
        super().__init__(address, ReportHandler)

    def process_request(self, request, client_address):
        if not self.slots.acquire(blocking=False):
            request.close()
            return
        try:
            super().process_request(request, client_address)
        except BaseException:
            self.slots.release()
            raise

    def process_request_thread(self, request, client_address):
        try:
            super().process_request_thread(request, client_address)
        finally:
            self.slots.release()


class ReportHandler(BaseHTTPRequestHandler):
    server_version = "JTSR"
    sys_version = ""

    def setup(self):
        super().setup()
        self.connection.settimeout(15)

    def log_request(self, code="-", size="-"):
        # No query strings, cookies, login bodies or report contents in access logs.
        self.log_message("%s %s", self.command, code)

    def respond(self, code, body, content_type="application/json; charset=utf-8", headers=None):
        if not isinstance(body, bytes):
            body = json.dumps(body, ensure_ascii=False, allow_nan=False).encode()
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Content-Security-Policy", "default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'")
        for name, value in (headers or {}).items():
            self.send_header(name, value)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def token(self):
        cookie = SimpleCookie()
        try:
            cookie.load(self.headers.get("Cookie", ""))
            return cookie["jtsr_session"].value if "jtsr_session" in cookie else ""
        except Exception:
            return ""

    def cookie(self, token, max_age):
        value = f"jtsr_session={token}; Path={self.server.base_path}/; HttpOnly; SameSite=Strict; Max-Age={max_age}"
        return value + ("; Secure" if self.server.secure_cookie else "")

    def do_POST(self):
        try:
            self.post()
        except (ValueError, OSError):
            self.respond(400, {"error": "请求无效"})

    def post(self):
        path = urlsplit(self.path).path
        if path not in {self.server.base_path + "/api/login", self.server.base_path + "/api/logout"}:
            return self.respond(404, {"error": "未找到"})
        origin = self.headers.get("Origin")
        scheme = "https" if self.server.secure_cookie else "http"
        if origin != f"{scheme}://{self.headers.get('Host', '')}":
            return self.respond(403, {"error": "来源校验失败"})
        if self.headers.get("Transfer-Encoding") or self.headers.get("Content-Type", "").split(";")[0] != "application/json":
            return self.respond(400, {"error": "需要 JSON 请求"})
        size = int(self.headers.get("Content-Length", "0"))
        if not 0 < size <= 8192:
            return self.respond(413, {"error": "请求过大或为空"})
        body = json.loads(self.rfile.read(size))
        if not isinstance(body, dict):
            return self.respond(400, {"error": "请求无效"})
        if path.endswith("/logout"):
            self.server.auth.logout(self.token())
            return self.respond(200, {"ok": True}, headers={"Set-Cookie": self.cookie("", 0)})
        username, password = body.get("username", ""), body.get("password", "")
        if not isinstance(username, str) or not isinstance(password, str) or len(username) > 64 or len(password) > 512:
            return self.respond(400, {"error": "账号格式无效"})
        token, status = self.server.auth.login(username, password)
        if token:
            return self.respond(200, {"ok": True}, headers={"Set-Cookie": self.cookie(token, 8 * 3600)})
        return self.respond(status, {"error": "尝试过于频繁，请 5 分钟后再试" if status == 429 else "账号或密码错误"},
                            headers={"Retry-After": "300"} if status == 429 else None)

    def do_HEAD(self):
        self.do_GET()

    def do_GET(self):
        try:
            self.get()
        except (FileNotFoundError, NotADirectoryError, PermissionError):
            self.respond(404, {"error": "报告不存在或不可访问"})
        except (ValueError, RecursionError):
            self.respond(422, {"error": "报告无法读取或超过安全大小限制"})
        except (BrokenPipeError, ConnectionResetError):
            pass
        except OSError:
            self.respond(404, {"error": "报告暂时不可用"})

    def get(self):
        url = urlsplit(self.path)
        path = unquote(url.path)
        base = self.server.base_path
        if path == base:
            return self.respond(302, b"", headers={"Location": base + "/"})
        if not path.startswith(base + "/"):
            return self.respond(404, {"error": "未找到"})
        route = path[len(base):]
        if route == "/api/health":
            return self.respond(200, {"ok": True})
        static = {"/": ("index.html", "text/html; charset=utf-8"),
                  "/assets/finding-view.js": ("finding-view.js", "text/javascript; charset=utf-8"),
                  "/assets/app.js": ("app.js", "text/javascript; charset=utf-8"),
                  "/assets/style.css": ("style.css", "text/css; charset=utf-8")}
        if route in static:
            name, content_type = static[route]
            return self.respond(200, (ASSETS / name).read_bytes(), content_type)
        if not self.server.auth.valid(self.token()):
            return self.respond(401, {"error": "请先登录"})
        if route == "/api/session":
            return self.respond(200, {"username": self.server.auth.username})
        query = parse_qs(url.query)
        if route == "/api/runs":
            page = max(1, int(query.get("page", ["1"])[0]))
            ids = self.server.store.run_ids()
            start = (page - 1) * 30
            return self.respond(200, {"runs": [self.server.store.summary(i) for i in ids[start:start+30]],
                                      "total": len(ids), "page": page, "page_size": 30})
        match = re.fullmatch(r"/api/runs/([A-Za-z0-9][A-Za-z0-9._-]{0,159})(?:/(artifact|download))?", route)
        if not match:
            return self.respond(404, {"error": "未找到"})
        run_id, action = match.groups()
        if action == "download":
            if not self.server.archive_slot.acquire(blocking=False):
                return self.respond(429, {"error": "正在生成其他压缩包，请稍后重试"})
            try:
                data = self.server.store.archive(run_id)
                return self.respond(200, data, "application/zip", {"Content-Disposition": f'attachment; filename="{run_id}.zip"'})
            finally:
                self.server.archive_slot.release()
        if action == "artifact":
            artifact = query.get("path", [""])[0]
            data = self.server.store.read(run_id, artifact)
            # Never serve model-controlled Markdown/JSON as HTML.
            headers = {"Content-Disposition": f'attachment; filename="{artifact.split("/")[-1]}"'}
            return self.respond(200, data, "text/plain; charset=utf-8", headers)
        return self.respond(200, self.server.store.detail(run_id))


def serve(args):
    store = ReportStore(args.reports)
    try:
        with ReportServer((args.host, args.port), store, Auth(args.auth_file), args.base_path, args.secure_cookie) as server:
            print(f"Report portal listening on {args.host}:{args.port}{args.base_path}/", flush=True)
            try:
                server.serve_forever()
            except KeyboardInterrupt:
                pass
    finally:
        store.close()
    return 0
